### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by moElwan** [Dwayr/webApp#2]
Hello,
there's lot of questions needs clarification here like:
what the target of it?
If I want to contribute. what should be the steps?
is there any todo/feature list for the project yet? 
any standards to stick to?
I think this need to be very clear to keep any interested contributors on the track

Best of luck

**Comment by komtcho** [comment]
We are now working on a project development plan and we will be ready in the next few days. You can join the project plan if you like .
Thank you .
